#!/usr/bin/env python3

"""
The `BaseModel` class defines a base model
with unique ID and timestamps for creation and last
update, along with methods for saving and converting to a dictionary format.
"""

from datetime import datetime
import uuid
import models as models
from __init__ import storage

class BaseModel:
    """BaseModel class defines a base model with unique ID and timestamps."""

    def __init__(self, *args, **kwargs):
        """Initialize object with unique ID and timestamps.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.

        Returns:
            None

        Raises:
            None

        This method initializes an instance of the BaseModel class,
        assigning it a unique ID generated by uuid.uuid4() and
        setting the creation and last update timestamps to the current datetime.
        If keyword arguments are provided, it updates the corresponding attributes.
        """
        self.id = str(uuid.uuid4())
        self.created_at = datetime.now()
        self.updated_at = datetime.now()

        if kwargs:
            for key, value in kwargs.items():
                if key == "created_at" or key == "updated_at":
                    setattr(self, key, datetime.fromisoformat(value))
                elif key != "__class__":
                    setattr(self, key, value)
                    
        else:
            self.id = str(uuid.uuid4())
            self.created_at = datetime.now()
            self.updated_at = datetime.now()

    def __str__(self):
        """Return string representation of the object.

        Args:
            None

        Returns:
            str: A string representation of the object in the format "[<class_name>] (<id>) <__dict__>".

        Raises:
            None

        This method returns a string representation of the object,
        including its class name, ID, and dictionary of attributes.
        """
        return f"[{self.__class__.__name__}] ({self.id}) {self.__dict__}"

    def save(self):
        """Update the 'updated_at' timestamp.

        Args:
            None

        Returns:
            None

        Raises:
            None

        This method updates the 'updated_at' timestamp of the object to the current datetime,
        and then saves the object to the storage.
        """
        self.updated_at = datetime.now()
        storage.new(self)
        storage.save()

    def to_dict(self):
        """Convert object to a dictionary.

        Args:
            None

        Returns:
            dict: A dictionary representation of the object,
                including its class name, ID, and dictionary of attributes.

        Raises:
            None

        This method converts the object to a dictionary format,
        including its class name, ID, and dictionary of attributes.
        """
        dic = dict()
        dic["__class__"] = self.__class__.__name__
        dic["id"] = self.id
        dic["created_at"] = self.created_at.isoformat()
        dic["updated_at"] = self.updated_at.isoformat()
        for key, value in self.__dict__.items():
            if key not in ("id", "created_at", "updated_at"):
                dic[key] = value
        return dic
